name: shared_theme_flutter
description: Flutter plugin to easily share a theme between Flutter and the web.
version: 0.0.1
author: Jacob Phillips <jifalops@gmail.com>
homepage: https://github.com/jifalops/shared_theme_flutter

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  shared_theme: ^0.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

